# Generated by Django 3.1.14 on 2023-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retailer', models.CharField(max_length=180, unique=True)),
                ('cron_time', models.TimeField()),
                ('retailer_url', models.CharField(max_length=180, unique=True)),
                ('proxy_used', models.CharField(choices=[('Residential', 'Residential'), ('Non-residential', 'Non-residential'), ('None', 'None')], default='United Kingdom', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Retailers',
            },
        ),
    ]
