# Generated by Django 3.1.14 on 2023-02-20 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailers',
            name='table_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=180, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailers',
            name='proxy_used',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Non-residential', 'Non-residential'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
